# Generated by Django 5.2.4 on 2025-07-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admin Profile', 'verbose_name_plural': 'Admin Profiles'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
        migrations.AlterModelOptions(
            name='monitoringprofile',
            options={'verbose_name': 'Monitoring Profile', 'verbose_name_plural': 'Monitoring Profiles'},
        ),
        migrations.AlterModelOptions(
            name='operatorprofile',
            options={'ordering': ['client__company_name', 'full_name'], 'verbose_name': 'Operator Profile', 'verbose_name_plural': 'Operator Profiles'},
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='users.clientprofile', verbose_name='Tegishli client'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_person',
            field=models.CharField(max_length=100, verbose_name='Aloqa shaxsi'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('basic', "Boshlang'ich"), ('standard', 'Standart'), ('premium', 'Premium'), ('enterprise', 'Korporativ')], default='basic', max_length=20, null=True, verbose_name='Obuna turi'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='domen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domen'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
